% ------------------------------------------------------
% This function returns the path to a data file depending on the given
% subject and dataset string. 
% ------------------------------------------------------
% Technische Universität Darmstadt
% Department of Computer Science
% Simulation, Systems Optimization and Robotics Group
% Janis Wojtusch (wojtusch@sim.tu-darmstadt.de), 2015
% Licensed under BSD 3-Clause License
% ------------------------------------------------------

function file = getFile(subject, dataset)

file = 0;
if (strcmp(subject, 'A') || strcmp(subject, 'B'))
    if strcmp(subject, 'A')
        localPaths = struct(...
            'm11', ['A', filesep, '1.1.mat'], ...
            'm12', ['A', filesep, '1.2.mat'], ...
            'm13', ['A', filesep, '1.3.mat'], ...
            'm21', ['A', filesep, '2.1.mat'], ...
            'm22', ['A', filesep, '2.2.mat'], ...
            'm23', ['A', filesep, '2.3.mat'], ...
            'm3', ['A', filesep, '3.mat'], ...
            'm4', ['A', filesep, '4.mat'], ...
            'm51', ['A', filesep, '5.1.mat'], ...
            'm52', ['A', filesep, '5.2.mat'], ...
            'm6', ['A', filesep, '6.mat'], ...
            'm7', ['A', filesep, '7.mat'], ...
            'm8', ['A', filesep, '8.mat'] ...
            );
    elseif strcmp(subject, 'B')
        localPaths = struct(...
            'm11', ['B', filesep, '1.1.mat'], ...
            'm12', ['B', filesep, '1.2.mat'], ...
            'm13', ['B', filesep, '1.3.mat'], ...
            'm21', ['B', filesep, '2.1.mat'], ...
            'm22', ['B', filesep, '2.2.mat'], ...
            'm23', ['B', filesep, '2.3.mat'], ...
            'm3', ['B', filesep, '3.mat'], ...
            'm4', ['B', filesep, '4.mat'], ...
            'm51', ['B', filesep, '5.1.mat'], ...
            'm52', ['B', filesep, '5.2.mat'], ...
            'm6', ['B', filesep, '6.mat'], ...
            'm7', ['B', filesep, '7.mat'], ...
            'm8', ['B', filesep, '8.mat'] ...
            );
    end
    dataset = strrep(dataset, '.', '');
    dataset = strcat('m', dataset);
    globalPath = getPath;
    if isfield(localPaths, dataset)
        localPath = localPaths.(dataset);
        file = [globalPath, filesep, localPath];
    end
    if ~isnumeric(file) && ~exist(file, 'file')
        fprintf('ERROR: File not found! Please modify the global path in getPath.m and the local paths in getFile.m.\n');
    end
end

end
