% ------------------------------------------------------
% This function returns the path to a data file depending on the given
% subject and dataset string. 
% ------------------------------------------------------
% Technische Universität Darmstadt
% Department of Computer Science
% Simulation, Systems Optimization and Robotics Group
% Janis Wojtusch (wojtusch@sim.tu-darmstadt.de), 2015
% Licensed under BSD 3-Clause License
% ------------------------------------------------------

function file = getFile(subject, dataset)
file = 0;
if (strcmp(subject, 'A') || strcmp(subject, 'B'))
    if strcmp(subject, 'A')
        localPaths = struct(...
            'm11', '1.1 Straight walking 1.0/A/Straight walking 1.0.mat',...
            'm12', '1.2 Straight walking 1.5/A/Straight walking 1.5.mat',...
            'm13', '1.3 Straight walking 2.0/A/Straight walking 2.0.mat',...
            'm21', '2.1 Straight running 2.0/A/Straight running 2.0.mat',...
            'm22', '2.2 Straight running 3.0/A/Straight running 3.0.mat',...
            'm23', '2.3 Straight running 4.0/A/Straight running 4.0.mat',...
            'm3', '3 Sideways walking/A/Sideways walking.mat',...
            'm4', '4 Transition/A/Transition.mat',...
            'm51', '5.1 Avoiding a long box obstacle/A/Avoiding a long box obstacle.mat',...
            'm52', '5.2 Avoiding a wide box obstacle/A/Avoiding a wide box obstacle.mat',...
            'm6', '6 Squats/A/Squats.mat',...
            'm7', '7 Kicks/A/Kicks.mat',...
            'm8', '8 Jumps/A/Jumps.mat',...
            'm91', '9 Additional datasets/A/9.1 Straight walking 1.0/Straight walking 1.0.mat',...
            'm92', '9 Additional datasets/A/9.2 Straight running 2.0/Straight running 2.0.mat',...
            'm93', '9 Additional datasets/A/9.3 Straight running 3.0/Straight running 3.0.mat'...
            );
    elseif strcmp(subject, 'B')
        localPaths = struct(...
            'm11', '1.1 Straight walking 1.0/B/Straight walking 1.0.mat',...
            'm12', '1.2 Straight walking 1.5/B/Straight walking 1.5.mat',...
            'm13', '1.3 Straight walking 2.0/B/Straight walking 2.0.mat',...
            'm21', '2.1 Straight running 2.0/B/Straight running 2.0.mat',...
            'm22', '2.2 Straight running 3.0/B/Straight running 3.0.mat',...
            'm23', '2.3 Straight running 4.0/B/Straight running 4.0.mat',...
            'm3', '3 Sideways walking/B/Sideways walking.mat',...
            'm4', '4 Transition/B/Transition.mat',...
            'm51', '5.1 Avoiding a long box obstacle/B/Avoiding a long box obstacle.mat',...
            'm52', '5.2 Avoiding a wide box obstacle/B/Avoiding a wide box obstacle.mat',...
            'm6', '6 Squats/B/Squats.mat',...
            'm7', '7 Kicks/B/Kicks.mat',...
            'm8', '8 Jumps/B/Jumps.mat',...
            'm91', '9 Additional datasets/B/9.1 Straight walking 2.0/Straight walking 2.0.mat'...
            );
    end
    dataset = strrep(dataset, '.', '');
    dataset = strcat('m', dataset);
    globalPath = getPath;
    if isfield(localPaths, dataset)
        localPath = localPaths.(dataset);
        file = [globalPath, localPath];
    end
    if ~isnumeric(file) && ~exist(file, 'file')
        fprintf('ERROR: File not found! Please modify the global path in getPath.m and the local paths in getFile.m.\n');
    end
end
end