% ------------------------------------------------------
% This function returns the path to a data file depending on the given
% subject and dataset string. 
% ------------------------------------------------------
% Technische Universität Darmstadt
% Department of Computer Science
% Simulation, Systems Optimization and Robotics Group
% Janis Wojtusch (wojtusch@sim.tu-darmstadt.de), 2015
% Licensed under BSD 3-Clause License
% ------------------------------------------------------

function file = getFile(subject, dataset)
file = 0;
if (strcmp(subject, 'A') || strcmp(subject, 'B'))
    if strcmp(subject, 'A')
        localPaths = struct(...
            'm11', 'A/1.1.mat',...
            'm12', 'A/1.2.mat',...
            'm13', 'A/1.3.mat',...
            'm21', 'A/2.1.mat',...
            'm22', 'A/2.2.mat',...
            'm23', 'A/2.3.mat',...
            'm3', 'A/3.mat',...
            'm4', 'A/4.mat',...
            'm51', 'A/5.1.mat',...
            'm52', 'A/5.2.mat',...
            'm6', 'A/6.mat',...
            'm7', 'A/7.mat',...
            'm8', 'A/8.mat'...
            );
    elseif strcmp(subject, 'B')
        localPaths = struct(...
            'm11', 'B/1.1.mat',...
            'm12', 'B/1.2.mat',...
            'm13', 'B/1.3.mat',...
            'm21', 'B/2.1.mat',...
            'm22', 'B/2.2.mat',...
            'm23', 'B/2.3.mat',...
            'm3', 'B/3.mat',...
            'm4', 'B/4.mat',...
            'm51', 'B/5.1.mat',...
            'm52', 'B/5.2.mat',...
            'm6', 'B/6.mat',...
            'm7', 'B/7.mat',...
            'm8', 'B/8.mat'...
            );
    end
    dataset = strrep(dataset, '.', '');
    dataset = strcat('m', dataset);
    globalPath = getPath;
    if isfield(localPaths, dataset)
        localPath = localPaths.(dataset);
        file = [globalPath, localPath];
    end
    if ~isnumeric(file) && ~exist(file, 'file')
        fprintf('ERROR: File not found! Please modify the global path in getPath.m and the local paths in getFile.m.\n');
    end
end
end
